SET LINESIZE 100;
COLUMN BK_NAME FORMAT A20;
COLUMN BK_ADDRESS FORMAT A30;
SELECT * FROM Bank;

SET LINESIZE 100;
COLUMN BR_ID FORMAT A10;
COLUMN BR_NAME FORMAT A20;
COLUMN BR_ADDRESS FORMAT A30;
SELECT * FROM Branch;


SET LINESIZE 100;
COLUMN CUST_ID FORMAT 9999;
COLUMN CUST_NAME FORMAT A20;
COLUMN PHONE_NO FORMAT A20;
COLUMN ADDRESS FORMAT A30;
SELECT * FROM Customer;


SET LINESIZE 100;
COLUMN ACC_NO FORMAT 9999;
COLUMN ACC_TYPE FORMAT A10;
COLUMN BALANCE FORMAT 999999.99;
COLUMN BR_ID FORMAT A10;
SELECT * FROM Account;

SET LINESIZE 100;
COLUMN CUST_ID FORMAT 9999;
COLUMN ACC_NO FORMAT 9999;
SELECT * FROM Customer_Account;

SET LINESIZE 100;
COLUMN LOAN_ID FORMAT 9999;
COLUMN LOAN_TYPE FORMAT A20;
COLUMN AMOUNT FORMAT 999999.99;
COLUMN BR_ID FORMAT A10;
SELECT * FROM Loan;




SET LINESIZE 100;
COLUMN CUST_ID FORMAT 9999;
COLUMN LOAN_ID FORMAT 9999;
SELECT * FROM Customer_Loan;


